name: CI Sast
on: 
  push:
    branches:
      - 'none'
jobs:
  Build-app:
    name: CI Run the test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python vulnerable-flask-app.py &
      - name: Test curl
        run: curl http://127.0.0.1:8081/

  security:
    name: SAST Run the test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: AppThreat/sast-scan-action@v1.0.0
        with:
          output: reports
          type: "python"
      - uses: actions/upload-artifact@v1.0.0
        if: always()
        with:
          name: reports
          path: reports